auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
   registry.k8s.io/ingress-nginx/kube-webhook-certgen: willdockerhub/kube-webhook-certgen
   registry.k8s.io/ingress-nginx/controller willdockerhub/controller
