auth:
  registry.cn-shenzhen.aliyuncs.com:
    username: $USERNAME
    password: $PASSWORD
images:
   registry.k8s.io/ingress-nginx/kube-webhook-certgen: registry.cn-shenzhen.aliyuncs.com/slien_cloud/kube-webhook-certgen
   registry.k8s.io/ingress-nginx/controller: registry.cn-shenzhen.aliyuncs.com/slien_cloud/controller
